on:
  workflow_dispatch: {}
name: schema-sync

jobs:
  generate:
    name: Generate Patched Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
      - name: Set git identity
        run: |-
          git config user.name "cdklabs-automation"
          git config user.email "aws-cdk-dev+cdklabs@amazon.com"
      - name: Pull and Patch Schema
        id: gen
        uses: TheRealAmazonKendra/cdk-patched-schema-generator@main
      - name: Update Local Schema Files
        run: |-
          ls
          pwd
          ${{ gen.outputs.cdkTypes }} > src/specification/cdk-types.json
          ${{ gen.outputs.cdkResources }} > src/specification/cdk-resources.json
